---
- name: "create vlan"
  hosts: localhost
  vars:
   host: "192.168.1.31"
   username: "admin"
   password: ""
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: read csv
    read_csv:
      path: dmzcmb.csv
    register: cmdb

  - debug:
      var: cmdb.list

  - name: Create Adres Objects
    fortios_address:
      host: "{{ host }}"
      name:  "{{ item.hostname  }}"
      value: "{{ item.ip  }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: present
    loop: "{{ cmdb.list }}"


  - name: Configure interfaces.
    fortios_ipv4_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      id: "{{item.id}}"
      comment: "Created by ansible"
      src_intf: TRANS_InternetFw
      dst_intf: DMZ_PROD
      src_addr: all
      dst_addr: "{{item.hostname}}"
      service: ALL_ICMP
      nat: false
      state: present
      policy_action: accept
      logtraffic: disable
    loop: "{{cmdb.list}}"



