---
- name: "create vlan"
  hosts: localhost
  vars:
   host: "192.168.1.31"
   username: "admin"
   password: ""
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure interfaces.
    fortios_system_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      system_interface:
        name: "interface ansible"
        alias: "ansible alias"
        allowaccess: "ping"
        defaultgw: "enable"
        description: "ansible description"
        vdom: "root"
        type: "vlan"
        ip: 192.168.5.1/24
        interface: "port2"
