---
- name: "create vlan"
  hosts: localhost
  vars:
   host: "192.168.1.31"
   username: "admin"
   password: ""
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure interfaces.
    fortios_facts:
      https: false
      ssl_verify: false
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      gather_subset:
        - fact: 'system_interface_select'
    register: facts
   
  - debug:
      msg: "{{facts}}"
