---
- name: Create new fabric vlan
  hosts: fabric
  gather_facts: false
  connection: ssh
  tasks:
  - name: collect banner
    shell: cat /etc/issue.net
    register: banner
 
  - debug:
      msg: "{{banner}}"

  - debug:
      msg: "NO BANNER"
    when: banner['stdout'] ==  ""
  - debug:
      msg: "OK"
    when: banner['stdout'] !=  ""
  - debug:
      msg: "telnet disabled"
  
  - set_fact:
      telnet_result: COMPLIANT

  - set_fact:
      banner_result: COMPLIANT
    when: banner['stdout'] !=  ""

  - set_fact:
      banner_result: NOT COMPLIANT
    when: banner['stdout'] == ""


  - name: remove old files
    file:
      path: ../cumuluscomp.csv
      state: absent
    run_once: true
    delegate_to: localhost

  - copy:
      content: host,type,result
      dest: ../cumuluscomp.csv
    run_once: true
    delegate_to: localhost

  - lineinfile:
      path: ../cumuluscomp.csv
      line: "{{ansible_hostname}},telnet,{{ telnet_result }}"
    delegate_to: localhost

  - lineinfile:
      path: ../cumuluscomp.csv
      line: "{{ansible_hostname}},banner,{{ banner_result }}"
    delegate_to: localhost


