---
- name: Create new fabric vlan
  hosts: fabric
  gather_facts: false
  connection: ssh
  tasks:
  - name: Fetch port config
    fetch: dest=config/{{ansible_hostname}}/ports.conf src=/etc/cumulus/ports.conf flat=yes

  - name: Fetch interfaces Configuration
    fetch: dest=config/{{ansible_hostname}}/interfaces src=/etc/network/interfaces flat=yes

  - name: Fetch FRR daemons file
    fetch: dest=config/{{ansible_hostname}}/daemons src=/etc/frr/daemons flat=yes

  - name: Fetch frr.conf
    fetch: dest=config/{{ansible_hostname}}/frr.conf src=/etc/frr/frr.conf flat=yes
