--- 
- name: Backup fortigate
  hosts: localhost
  vars:
    host: 192.168.1.31
    username: admin
    password: ""
  tasks:
  - name: Backup current config
    fortios_config:
      host: "{{host}}"
      username: "{{username}}"
      password: "{{password}}"
      backup: yes
      backup_path: config
#      backup_filename: backup
      filter: "firewall address"
