--- 
- name: Create new fabric vlan
  hosts: localhost
  vars:
    host: 192.168.1.31
    username: admin
    password: ""
    vdom: "root"
  tasks:
  - name: Backup current config
    fortios_config:
      host: "{{host}}"
      username: "{{username}}"
      password: "{{password}}"
      backup: yes
      backup_path: /root/network_automation/playbooks/backup/config
