--- 
- name: Backup vyos routers
  hosts: vyos
  connection: network_cli
  tasks:
  - name: Backup current config
    vyos_config:
      backup: yes
      backup_options:
        filename: vyos.conf
        dir_path: config
